name: b17-workflow

on: push

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - name: print message
        run: |
            sleep 10 
            echo "Hello world!!!!"
  second:
    runs-on: ubuntu-22.04-arm
    steps:
      - name: Print message for second job
        run: |
            sleep 10
            echo "This is my second job"